### ISSUE TITLE
Possible XPA communication problem on Mac OS 10.8.5

### ISSUE THREAD

**Issue by sosey** [spacetelescope/imexam#26]
Connection timeout with the ds9. Try to increase the *wait_time* parameter (current value is  10 s)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lubeda/astronomy/site-packages/lib/imexam-0.3.dev-py2.7-macosx-10.6-x86_64.egg/imexam/connect.py", line 62, in __init__
    target=target, path=path, wait_time=wait_time, quit_ds9_on_del=quit_window)
  File "/Users/lubeda/astronomy/site-packages/lib/imexam-0.3.dev-py2.7-macosx-10.6-x86_64.egg/imexam/ds9_viewer.py", line 213, in __init__
    self._set_frameinfo()  # initial load
  File "/Users/lubeda/astronomy/site-packages/lib/imexam-0.3.dev-py2.7-macosx-10.6-x86_64.egg/imexam/ds9_viewer.py", line 246, in _set_frameinfo
    frame = self.frame()
  File "/Users/lubeda/astronomy/site-packages/lib/imexam-0.3.dev-py2.7-macosx-10.6-x86_64.egg/imexam/ds9_viewer.py", line 886, in frame
    frame = self.get("frame").strip()  # xpa returns '\n' for no frame
  File "/Users/lubeda/astronomy/site-packages/lib/imexam-0.3.dev-py2.7-macosx-10.6-x86_64.egg/imexam/ds9_viewer.py", line 617, in get
    return self.xpa.get(param)
  File "/Users/lubeda/astronomy/site-packages/lib/imexam-0.3.dev-py2.7-macosx-10.6-x86_64.egg/imexam/xpa_wrap.py", line 12, in get
    r = xpa.get(self, param.encode("ascii"))
  File "xpa.pyx", line 172, in xpa.xpa.get (wrappers/xpa.c:1797)
  File "xpa.pyx", line 112, in xpa._get (wrappers/xpa.c:1037)
xpa.XpaException: XPA$ERROR: no response from server during handshake (?:?)
```

**Comment by sosey** [comment]
Don't see this problem anymore
