### ISSUE TITLE
imexam v0.9.1 fails to import with astropy v6

### ISSUE THREAD

**Issue by KathleenLabrie** [spacetelescope/imexam#263]
imexam won't import with astropy v6.   (python 3.10)

```
>>> import imexam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/klabrie/condaenvs/susd3.10_20240130/lib/python3.10/site-packages/imexam/__init__.py", line 10, in <module>
    from ._astropy_init import *
  File "/Users/klabrie/condaenvs/susd3.10_20240130/lib/python3.10/site-packages/imexam/_astropy_init.py", line 29, in <module>
    from astropy.config.configuration import (
ImportError: cannot import name 'update_default_config' from 'astropy.config.configuration' (/Users/klabrie/condaenvs/susd3.10_20240130/lib/python3.10/site-packages/astropy/config/configuration.py)
```

**Comment by sosey** [comment]
@KathleenLabrie thank you - I desperately would like to find some time to update this package, It's been languishing too long as I was made the sole developer, and only in my free time. Is there anyone at gemini that can help with bringing this up to speed?  Are you all actively using this package?

**Comment by KathleenLabrie** [comment]
Sorry, I was in the middle of two big package releases and then forgot about this.  

No, we absolutely do not have resources available.  We're even losing people and barely able to keep our head above water.  

We are using imexam for some Ops tools.  

What does STScI use to display images in something like ds9 or ginga?  If it needs that functionality, I guess.

**Comment by sosey** [comment]
I completely understand!  

Right now they are only supporting JdaViz, which is its own viewer. You might see if that fits your needs?
https://github.com/spacetelescope/jdaviz

In my personal time I'll see if I can fix the major issues here in imexam so that your ops aren't affected - apologies I cant respond too fast these days!

**Comment by KathleenLabrie** [comment]
As far as I can see JdaViz cannot help us.  We need to display from real
python scripts, not from jupyter notebooks.   I tried to run python in a
shell and display to imviz layout, it tells me that I need a jupyter
notebook (Ops tools are real scripts not interactive notebooks) or use the
command line and load files manually.  So yeah, not useful at all.   It's
unfortunate that it is locked in a jupyter framework.

We need a tool we can use for real app coding not interactive analysis.

For the astropy v6 import, I found that the code in `master` is successful
at importing v6.  I'm not sure of the implication though as I don't
understand what imexam is trying to do by importing the now gone functions
in astropy.
