### ISSUE TITLE
The current version of ginga breaks imexam

### ISSUE THREAD

**Issue by sosey** [spacetelescope/imexam#35]
The current version of ginga does not work with imexam because the objects it calls were deleted or moved. I need to find the replacement and get it up and running again. The last version that worked was from april 15, 2015: 7528d3deb9f7839d0c58cd90f9e237a2cc116487

**Comment by pllim** [comment]
What objects? Is there a traceback?

**Comment by sosey** [comment]
798         # Ginga imports for matplotlib backend
    799         from ginga.mplw.ImageViewCanvasMpl import ImageViewCanvas
--> 800         from ginga.mplw.ImageViewCanvasTypesMpl import DrawingCanvas
    801 
    802         # create a regular matplotlib figure

ImportError: cannot import name 'DrawingCanvas'


I see that he's done some work in this module, and created a new ipg module, I just haven't had time to check it out.

**Comment by pllim** [comment]
Yeah, there is a `ginga/mplw/ipg.py` now (see  below). Looks like `DrawingCanvas` is now generated by `CustomMplViewer.add_canvas()` method.

```python
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

from ginga.mplw.ImageViewCanvasMpl import ImageViewCanvas
from ginga.misc import log
from ginga.AstroImage import AstroImage
from ginga import cmap
# add matplotlib colormaps to ginga's own set
cmap.add_matplotlib_cmaps()

## from IPython.display import Image
## from io import BytesIO


class CustomMplViewer(ImageViewCanvas):

    def get_nb_image(self):
        return Image(data=bytes(self.get_rgb_image_as_bytes(format='png')),
                     format='png', embed=True)

    def load(self, filepath):
        image = AstroImage(logger=self.logger)
        image.load_file(filepath)

        self.set_image(image)

    def show(self):
        self.figure.show()

    def add_canvas(self, tag=None):
        # add a canvas to the view
        DrawingCanvas = self.getDrawClass('drawingcanvas')
        canvas = DrawingCanvas()
        # enable drawing on the canvas
        canvas.enable_draw(True)
        canvas.enable_edit(True)
        canvas.ui_setActive(True)
        canvas.setSurface(self)
        # add the canvas to the view.
        self.add(canvas, tag=tag)
        return canvas


def get_viewer():
    # Set to True to get diagnostic logging output
    use_logger = False
    logger = log.get_logger(null=not use_logger, log_stderr=True)

    # create a regular matplotlib figure
    fig = plt.figure()

    # create a ginga object, initialize some defaults and
    # tell it about the figure
    viewer = CustomMplViewer(logger)
    viewer.enable_autocuts('on')
    viewer.set_autocut_params('zscale')
    viewer.set_figure(fig)

    # enable all interactive ginga features
    viewer.get_bindings().enable_all(True)

    return viewer
```

**Comment by sosey** [comment]
yah, I saw that. I just haven't had time to try fixing the code. Feel free if you have time ; )

**Comment by pllim** [comment]
How do I test it?

**Comment by pllim** [comment]
I have a theoretical fix (untested):
```python
class ginga_mp(ginga_general):

    """
    A ginga-based viewer that uses a matplotlib widget.

    This kind of viewer has slower performance than if we
    choose a particular widget back end, but the advantage is that
    it works so long as the user has a working matplotlib.

    This implementation has the benefit of adding image overlays
    """

    def _create_viewer(self, bind_prefs, viewer_prefs):

        # Ginga imports for matplotlib backend
        from ginga.mplw import ipg

        self.ginga_view = ipg.get_viewer()
        self.figure = self.ginga_view.figure

        #self.figure.show()

        # create a canvas that we insert when doing imexam mode
        self.canvas = self.ginga_view.add_canvas()
```

**Comment by sosey** [comment]
Right now, just install imexam, ginga and dependencies and then try it out in a session, 

import imexam
a=imexam.connect(viewer='ginga_mp')


I still need to create a good set of tests to monitor the non-interactive parts of the package too.

**Comment by pllim** [comment]
Hah, I can't get `imexam` to load on my Anaconda env.
```
Python 2.7.10 |Anaconda 2.1.0 (64-bit)| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import imexam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/internal/sc1/anaconda/lib/python2.7/site-packages/imexam-0.5.2-py2.7-linux-x86_64.egg/imexam/__init__.py", line 7, in <module>
    from .util import *
  File "/internal/sc1/anaconda/lib/python2.7/site-packages/imexam-0.5.2-py2.7-linux-x86_64.egg/imexam/util.py", line 12, in <module>
    from . import xpa
ImportError: /internal/sc1/anaconda/lib/python2.7/site-packages/imexam-0.5.2-py2.7-linux-x86_64.egg/imexam/xpa.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
```

**Comment by sosey** [comment]
Do you have cython in there? It usu prints a warning, but try to conda install cython (it also wants scipy, astropy, numpy)

**Comment by pllim** [comment]
Yes to all
```python
>>> import cython
>>> cython.__version__
'0.22'
>>> import numpy
>>> numpy.__version__
'1.9.2'
>>> import scipy
>>> scipy.__version__
'0.15.1'
>>> import astropy
>>> astropy.__version__
u'1.0.3'
```

**Comment by pllim** [comment]
Okay, never mind. I wiped old build and that fixed it.

**Comment by sosey** [comment]
good .. cause I just created a new env and install everything and it seemed to work, phew :)

**Comment by sosey** [comment]
You'll probably want to try using TkAgg as your mpl backend too, though at one point nbAgg also worked for me in the notebook

**Comment by pllim** [comment]
Nope, it works now. I'll submit a PR.

**Comment by sosey** [comment]
Did you also make sure that an image would display in a window?

**Comment by pllim** [comment]
Yes, I opened a FITS image. Didn't do full analysis though. Just said, "It's full of stars!" and closed it.

**Comment by embray** [comment]
:laughing:
