### ISSUE TITLE
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'

### ISSUE THREAD

**Issue by Gabriel-p** [spacetelescope/imexam#75]
I'm trying to install this package in a `pyenv` with Python 3.5.2 installed. This is what I get:

```
$ pip install imexam
Collecting imexam
  Using cached imexam-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers pacakge.  Attempting download instead.
    Downloading astropy_helpers; run setup.py with the --offline option to force offline installation.
    /home/gabriel/.pyenv/versions/3.5.2/envs/photom-env/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
      warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
    /home/gabriel/.pyenv/versions/3.5.2/envs/photom-env/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
      warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nwed80dj/imexam/setup.py", line 27, in <module>
        conf = config.ConfigParser()
    AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
```

**Comment by sosey** [comment]
@Gabriel-p Sorry, this is an old binary of imexam, I've been away and haven't had a chance to upload the recent binaries to pypi, try installing from the repo itself, you can either clone and install or use pip:
pip install:

pip install git+https://github.com/spacetelescope/imexam

**Comment by Gabriel-p** [comment]
Worked flawlessly. Thanks @sosey!

**Comment by sosey** [comment]
excellent! Feel free to comment back on any other issues or suggestions you have while using the library :)

**Comment by Gabriel-p** [comment]
Sorry to bother you again @sosey, but I can't seem to be able to load the package. It is apparently installed:

```
$ pip freeze
astropy==1.2.1
cycler==0.10.0
Cython==0.24.1
dask==0.11.0
decorator==4.0.10
imexam==0.6.3.dev256
ipython==5.1.0
ipython-genutils==0.1.0
matplotlib==1.5.3
networkx==1.11
numpy==1.11.1
pexpect==4.2.1
photutils==0.3.dev2120
pickleshare==0.7.4
Pillow==3.4.0
prompt-toolkit==1.0.8
ptyprocess==0.5.1
Pygments==2.1.3
pyparsing==2.1.9
python-dateutil==2.5.3
pytz==2016.7
scikit-image==0.12.3
scipy==0.18.1
simplegeneric==0.8.1
six==1.10.0
toolz==0.8.0
traitlets==4.3.1
wcwidth==0.1.7
```

but attempting to run the example shown in the `README.md` file:

```
from imexam import Imexamine
import numpy as np

plots = Imexamine()
data = np.random.rand(100,100) * np.ones((100,100))
plots.plot_line(35,45,data) #shows a matplotlib window with a plot
plots.save() #saves the current plot to file
```

results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Imexamine'
```

**Comment by sosey** [comment]
... world series break...

sorry, think this is my typo in the readme, Imexamine is the class  in imexamine (of the package imexam - yah, sorry, that is a little confusing) but try this:

from imexam.imexamine import Imexamine
plots=Imexamine()

where the plots object now has all the functions attached to it

note: this is the way to use the library without any visual interaction (i.e. without DS9 or Ginga) 
So the rest of the example makes a fake 2D data array and then makes a line plot at an x,y point
